export const INVOICE_ADDED = 'INVOICE_ADDED';
export const INVOICE_FETCHED = 'INVOICE_FETCHED';
export const INVOICE_SCHEDULED = 'INVOICE_SCHEDULED';
export const TOPICS_SUBSCRIBED = 'TOPICS_SUBSCRIBED';
export const INVOICE_STATUS_CHANGED = 'INVOICE_STATUS_CHANGED';